# This file was added by Pulumi and should not be edited manually. To edit the contents of this file, please go
# to the github-management project in moneymeets-pulumi and call `pulumi up` after changing the template file.

name: Merge checks

on:
  push:
    branches:
      - feature/**
  pull_request_target:

jobs:
  merge-checks:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    timeout-minutes: 5
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/github-script@v7
        id: get-head-hash
        with:
          result-encoding: string
          script: |
            core.setOutput("value", context.eventName == "pull_request_target" ? context.payload.pull_request.head.sha : context.sha);

      - name: Merge checks
        uses: moneymeets/action-merge-checks@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head_sha: ${{ steps.get-head-hash.outputs.value }}
